/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Instruktor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.KlijentskiZahtev;
import komunikacija.KomunikacijaSaServerom;
import komunikacija.ServerskiOdgovor;
import operacije.Operacije;

/**
 *
 * @author HP
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lblUlogovani.setText(kontroler.Kontroler.getInstance().getInstruktor().getIme() + " " + kontroler.Kontroler.getInstance().getInstruktor().getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUlogovani = new javax.swing.JLabel();
        btnNoviTecaj = new javax.swing.JButton();
        btnPregledTecaja = new javax.swing.JButton();
        btnUpisiClana = new javax.swing.JButton();
        btnPretraziClanove = new javax.swing.JButton();
        btnPregledTermina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plesni klub");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Ulogovani instruktor:");

        lblUlogovani.setText("jLabel2");

        btnNoviTecaj.setText("Kreiraj novi tecaj");
        btnNoviTecaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviTecajActionPerformed(evt);
            }
        });

        btnPregledTecaja.setText("Pregled tecaja");
        btnPregledTecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledTecajaActionPerformed(evt);
            }
        });

        btnUpisiClana.setText("Upisi clana");
        btnUpisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpisiClanaActionPerformed(evt);
            }
        });

        btnPretraziClanove.setText("Pretrazi clanove");
        btnPretraziClanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziClanoveActionPerformed(evt);
            }
        });

        btnPregledTermina.setText("Pregled zakazanih termina");
        btnPregledTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledTerminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUlogovani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPregledTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnPregledTecaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNoviTecaj, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPretraziClanove, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1)
                    .addComponent(lblUlogovani))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoviTecaj, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPregledTecaja, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziClanove, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPregledTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logout();
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNoviTecajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviTecajActionPerformed
        NoviTecajForma ntf = new NoviTecajForma();
        ntf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ntf.setVisible(true);
    }//GEN-LAST:event_btnNoviTecajActionPerformed

    private void btnPregledTecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledTecajaActionPerformed
        PregledTecajaForma ptf = new PregledTecajaForma();
        ptf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ptf.setVisible(true);
    }//GEN-LAST:event_btnPregledTecajaActionPerformed

    private void btnUpisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpisiClanaActionPerformed
        UpisiClanaForma ucf = new UpisiClanaForma();
        ucf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ucf.setVisible(true);
    }//GEN-LAST:event_btnUpisiClanaActionPerformed

    private void btnPretraziClanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziClanoveActionPerformed
        PretraziClanoveForma pcf = new PretraziClanoveForma();
        pcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pcf.setVisible(true);
    }//GEN-LAST:event_btnPretraziClanoveActionPerformed

    private void btnPregledTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledTerminaActionPerformed
        PregledTerminaForma ptf = new PregledTerminaForma();
        ptf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ptf.setVisible(true);
    }//GEN-LAST:event_btnPregledTerminaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNoviTecaj;
    private javax.swing.JButton btnPregledTecaja;
    private javax.swing.JButton btnPregledTermina;
    private javax.swing.JButton btnPretraziClanove;
    private javax.swing.JButton btnUpisiClana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUlogovani;
    // End of variables declaration//GEN-END:variables

    private void logout() {
        try {
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(operacije.Operacije.LOGOUT);
            kz.setArgument(kontroler.Kontroler.getInstance().getInstruktor());

            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);

            ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();

            if (so.isUspesno()) {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Uspesno!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Greska!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(KomunikacijaSaServerom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
